services:
  db_customer:
    image: postgres:16
    container_name: db_customer
    environment:
      POSTGRES_USER: cust
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cust
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cust"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-service:
    build:
      context: ./services/customer-service
    container_name: customer-service
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://cust:pass@db_customer/customer_db
    depends_on:
      db_customer:
        condition: service_healthy
    ports:
      - "8081:8081"

  underwriting-service:
    build:
      context: ./services/underwriting-service
    container_name: underwriting-service
    environment:
      FLASK_ENV: production
      CUSTOMER_URL: http://customer-service:8081
    depends_on:
      customer-service:
        condition: service_started
    ports:
      - "8082:8082"



  # --- Postgres for Policy ---
  db_policy:
    image: postgres:16
    environment:
      POSTGRES_USER: policy
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: policy
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "policy"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Policy Service ---
  policy-service:
    build:
      context: ./services/policy-service
    container_name: policy-service
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://policy:pass@db_policy/policy_db
    depends_on:
      db_policy:
        condition: service_healthy
    ports:
      - "8083:8083"