version: "3.9"
services:
  db_customer:
    image: postgres:16
    environment: POSTGRES_USER=cust
               POSTGRES_PASSWORD=pass
               POSTGRES_DB=customer_db
    ports: ["5433:5432"]

  customer-service:
    build: ./services/customer-service
    environment: FLASK_ENV=production
    ports: ["8081:8081"]
    depends_on: [db_customer]

  underwriting-service:
    build: ./services/underwriting-service
    environment: FLASK_ENV=production
    ports: ["8082:8082"]
    depends_on: [customer-service]